# Generated by Django 4.1.7 on 2023-03-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen_service", "0002_remove_cook_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
